entries=['Basisvar-access-client_street-1%%Strasse',
'Basisvar-access-client_zipcode-1%%PLZ',
'Basisvar-access-client_city-1%%Ort',
'Basisvar-access-client_housenumber-1%%Hausnummer',
'Basisvar-access-client_stair-1%%Stiege',
'Basisvar-access-client_door-1%%Tür',
'Basisvar-access-contact_person-1%%Kontaktperson',
'Basisvar-access-contact_phone_private-1%%Telefonnummer (privat)',
'Basisvar-access-contact_phone_business-1%%Telefonnummer (geschäftlich)',
'Basisvar-access-contact_phone_mobile-1%%Mobilnummer',
'Basisvar-access-install_company_instructed-1%%Montagefirma beauftragt',
'Basisvar-access-hardware_serialnumber-1%%Modemseriennummer',
'Basisvar-access-traffic_limit-1%%Traffic Limit',
'Basisvar-cablemaster-cablemaster_contract-1%%Cablemaster Vertrag',
'Basisvar-cia-cia_interfacesetting_esa_port-1%%CIA Interfacesetting ESA Port',
'Basisvar-cia-cia_interfacesetting_esb_port-1%%CIA Interfacesetting ESB Port',
'Basisvar-cia-transmission_terminationpoint-1%%Transmission Terminationpoint',
'Basisvar-cia-equipment_commissioning-1%%Equipment-Inbetriebnahme',
'Basisvar-cia-router_port_esa-1%%Router-Port ESA',
'Basisvar-cia-router_serial_number-1%%Router-Seriennummer',
'Basisvar-cia-cia_upgrade-1%%Upgrade ja/nein',
'Basisvar-cia-cia_carrier-1%%Carrier',
'Basisvar-cia-service_id-1%%Service-ID',
'Basisvar-cia-circiut_id-1%%Circiut-ID',
'Basisvar-cia-cia_service_cafr_nr-1%%CAFR-Nr / Mietleitungsnummer*',
'Basisvar-cia-cia_service_bandwidth_cir-1%%Bandbreite / Mbit (CIR)*',
'Basisvar-cia-cia_service_bandwidth_eir-1%%Bandbreite / Mbit (EIR)',
'Basisvar-cia-cia_service_cafr_completion-1%%Herstellung lt. CAFR (KW)*',
'Basisvar-cia-cia_service_contract_period-1%%Vertragsdauer / Monate*',
'Basisvar-cia-cia_service_number-1%%Rufnummer / Testnummer',
'Basisvar-cia-cia_service_appointment-1%%Realisierungstermin (KW)',
'Basisvar-cia-cia_pina_company-1%%Firma*',
'Basisvar-cia-cia_pina_address-1%%Adresse*',
'Basisvar-cia-cia_pina_zipcode-1%%PLZ*',
'Basisvar-cia-cia_pina_city-1%%Ort*',
'Basisvar-cia-cia_pina_contact_name-1%%Kontakt - Name*',
'Basisvar-cia-cia_pina_contact_phone-1%%Kontakt - Telefon*',
'Basisvar-cia-cia_pina_interface-1%%Handover - Interface*',
'Basisvar-cia-cia_pinb_company-1%%Firma*',
'Basisvar-cia-cia_pinb_address-1%%Adresse*',
'Basisvar-cia-cia_pinb_zipcode-1%%PLZ*',
'Basisvar-cia-cia_pinb_city-1%%Ort*',
'Basisvar-cia-cia_pinb_contact_name-1%%Kontakt - Name*',
'Basisvar-cia-cia_pinb_contact_phone-1%%Kontakt - Telefon*',
'Basisvar-cia-cia_pinb_interface-1%%Handover - Interface*',
'Basisvar-cia-cia_pinb_switchdata-1%%Switchdaten*',
'Basisvar-cia-cia_mailrecipient-1%%Mailempfänger',
'Basisvar-cia-cia_order_type-1%%Order-Typ',
'Basisvar-line_mpls-line_street-1%%Strasse',
'Basisvar-line_mpls-line_housenr-1%%Hausnummer',
'Basisvar-line_mpls-line_stairway-1%%Stiege',
'Basisvar-line_mpls-line_floor-1%%Stock',
'Basisvar-line_mpls-line_door-1%%Türnummer',
'Basisvar-line_mpls-line_zipcode-1%%PLZ',
'Basisvar-line_mpls-line_city-1%%Ort',
'Basisvar-line_mpls-line_install_date_ta-1%%TA-Montage',
'Basisvar-line_mpls-contact_person-1%%Kontaktperson',
'Basisvar-line_mpls-contact_phone-1%%Kontaktperson (Tel)',
'Basisvar-mpls-vrf_id-1%%VRF ID',
'Basisvar-mpls-vrf_name-1%%VRF Name',
'Basisvar-mpls-line_backup-1%%Backupleitung',
'Basisvar-mpls-automatic_completion-1%%Automatische Fertigstellung',
'Basisvar-router_mpls-router_sn_master-1%%Router SerienNr (Master)',
'Basisvar-router_mpls-router_sn-1%%Router SerienNr (Slave)',
'Basisvar-xdsl-install_termin-1%%Umschaltezeitfenster',
'Basisvar-xdsl-ta_clientnr-1%%TA-KundenNr.',
'Basisvar-xdsl-prev_phone_areacode-1%%ehemalige Vorwahl',
'Basisvar-xdsl-prev_phone_number-1%%ehemalige Rufnummer',
'Basisvar-xdsl-installservice-1%%Vor-Ort Service',
'Basisvar-xdsl-xdsl_concentrator_gateway-1%%Konzentrator-Gateway',
'Basisvar-xdsl-xdsl_concentrator_submask-1%%Konzentrator-Submask',
'Basisvar-xdsl-username-1%%Username',
'Basisvar-xdsl-password-1%%Passwort',
'Basisvar-xdsl-xdsl_wan_ip-1%%WAN/LAN IP-Adresse (Modem)',
'Basisvar-xdsl-xdsl_kuda-1%%xDSL Kupferdoppeladern',
'Basisvar-xdsl-xdsl_speed-1%%Bandbreite',
'Basisvar-xdsl-traffic_limit-1%%Traffic Limit',
'Basisvar-xdsl-radius_max_logins-1%%Radius MaxLogins',
'Basisvar-xdsl-suppress_uzf_mail-1%%UZF Mails unterdrücken',
'Basisvar-qos-standard_service_percent-1%%Standard-Serviceklasse in Prozent',
'Basisvar-qos-advanced_service_percent-1%%Advanced-Serviceklasse in Prozent',
'Basisvar-qos-premium_service_percent-1%%Premium-Serviceklasse in Prozent',
'service_class_premium[]%%Serviceklasse Premium',
'Basisvar-router_mpls-hsrp-1%%HSRP',
'Basisvar-router_mpls-hsrp_gateway-1%%HSRP-IP (Gateway)',
'Basisvar-router_mpls-physical_ip-1%%Internal BGP-Neighbor IP',
'Basisvar-vull-vull_dslam_loc_id-1%%DSLAM-Location-ID',
'Basisvar-adsl-phone_areacode-1%%Vorwahl',
'Basisvar-adsl-phone_number-1%%Rufnummer',
'Basisvar-adsl-adsl_phone_type-1%%Anschlussart',
'Basisvar-adsl-ta_clientnr-1%%TA-KundenNr.',
'Basisvar-adsl-contact_person-1%%Kontaktperson',
'Basisvar-adsl-contact_phone-1%%Kontaktperson (Tel)',
'Basisvar-adsl-adsl_exist-1%%ADSL existiert',
'Basisvar-adsl-adsl_product_change-1%%ADSL Produktwechsel',
'Basisvar-adsl-adsl_si-1%%ADSL Self-Installation',
'Basisvar-client-client_company-1%%Firma',
'Basisvar-client-client_companycode-1%%Firmenbuchnummer',
'Basisvar-client-client_sex-1%%Geschlecht',
'Basisvar-client-client_firstname-1%%Vorname',
'Basisvar-client-client_lastname-1%%Nachname',
'Basisvar-client-client_street-1%%Strasse',
'Basisvar-client-client_zipcode-1%%PLZ',
'Basisvar-client-client_city-1%%Ort',
'Basisvar-client-client_phoneareacode-1%%Ortsvorwahl',
'Basisvar-client-client_phonenumber-1%%Rufnummer',
'Basisvar-cia-circiut_id-1%%Circiut-ID(1)',
'Basisvar-cia-circiut_id-2%%Circiut-ID(2)'
]

